# Jekyll configuration
name: Home
description: Puneet K. Dokania 
#profilepic: <img src="/images/profile_pic.png" />
profilepic: <img src="/images/puneet3.png" />
googlescholar: 'https://scholar.google.co.uk/citations?user=WsM7ybkAAAAJ&hl=en&oi=ao'

permalink: /:year/:month/:title
#permalink: /:title
paginate: 3

highlighter: rouge
markdown: kramdown
#kramdown:
#   footnote_backlink:   '&#x21a9;&#xfe0e;'
#   math_engine:         mathjax
#   math_engine_opts:
#     preview:           true
#     preview_as_code:   true
#
gems: ['jekyll-paginate']

